url: "https://www.opentargets.org/" 

title: "Open Targets" 

collections_dir: my_collections

collections:
  - jobs
    
plugins:
  - jekyll-get-json
  
jekyll_get_json:
  - data: ghost_api_response
    json: 'https://open-targets-blog.ghost.io/ghost/api/v3/content/posts/?key=6f5f3e6aa359bf5ad18bb2855d&include=authors&limit=20&fields=title,slug,meta_description,published_at'