name: PR previews
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]
concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  pages: write

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository   # no forks
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        if: github.event.action != 'closed'
        with:
          bundler-cache: true

      - name: jekyll build
        if: github.event.action != 'closed'
        run: |
          bundle exec jekyll build --baseurl "/pr-preview/pr-${{ github.event.number }}"
          touch _site/.nojekyll

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          pages-base-url: opentargets.org

      - name: Trigger Pages build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api -X POST repos/${{ github.repository }}/pages/builds
